; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
extra_scripts = pre:scripts/generate_pio_headers.py
	pre:scripts/set_progname.py
lib_deps = 
	adafruit/Adafruit TinyUSB Library@2.4.1
	adafruit/Adafruit SPIFlash@4.3.4
	adafruit/Adafruit NeoPixel@1.12.2
	adafruit/SdFat - Adafruit Fork@2.2.3
	fortyseveneffects/MIDI Library@5.0.2
build_flags =
	-DUSE_TINYUSB

[env:pico]
board = rpipico
build_flags =
	${env.build_flags}
	-DBOARD_PICO

[env:rp2040_zero]
board = waveshare_rp2040_zero
build_flags =
	${env.build_flags}
	-DBOARD_RP2040_ZERO
