Import("env")  # type: ignore[name-defined]

from pathlib import Path
import re


PROJECT_SRC_DIR = Path(env.subst("$PROJECT_SRC_DIR"))  # type: ignore[name-defined]


def _sanitize_instruction(line: str) -> str:
    line = line.split(";", 1)[0]
    return line.strip()


def _normalize_program_name(name: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]", "_", name)


def _encode_mov(args: str) -> str:
    parts = [p.strip().lower() for p in args.split(",")]
    if len(parts) != 2:
        raise ValueError(f"Invalid mov syntax: {args}")
    dst, src = parts
    return f"(uint16_t)pio_encode_mov(pio_{dst}, pio_{src})"


def _encode_in(args: str) -> str:
    parts = [p.strip().lower() for p in args.split(",")]
    if len(parts) != 2:
        raise ValueError(f"Invalid in syntax: {args}")
    src, bit_count = parts
    return f"(uint16_t)pio_encode_in(pio_{src}, {bit_count})"


def _encode_push(args: str) -> str:
    mode = args.strip().lower()
    if mode == "noblock":
        return "(uint16_t)pio_encode_push(false, false)"
    if mode == "block" or mode == "":
        return "(uint16_t)pio_encode_push(false, true)"
    raise ValueError(f"Unsupported push mode: {args}")


def _encode_jmp(args: str, labels: dict[str, int]) -> str:
    parts = [p.strip().lower() for p in args.split(",")]
    if len(parts) == 1:
        target = parts[0]
        if target not in labels:
            raise ValueError(f"Unknown label for jmp: {target}")
        return f"(uint16_t)pio_encode_jmp({labels[target]})"

    if len(parts) != 2:
        raise ValueError(f"Invalid jmp syntax: {args}")

    condition, target = parts
    if target not in labels:
        raise ValueError(f"Unknown label for jmp: {target}")

    cond_map = {
        "!x": "pio_encode_jmp_not_x",
        "x--": "pio_encode_jmp_x_dec",
        "!y": "pio_encode_jmp_not_y",
        "y--": "pio_encode_jmp_y_dec",
        "x != y": "pio_encode_jmp_x_ne_y",
        "pin": "pio_encode_jmp_pin",
        "!osre": "pio_encode_jmp_not_osre",
    }

    if condition not in cond_map:
        raise ValueError(f"Unsupported jmp condition: {condition}")

    return f"(uint16_t){cond_map[condition]}({labels[target]})"


def _encode_instruction(instr: str, labels: dict[str, int]) -> str:
    op, _, args = instr.partition(" ")
    op = op.strip().lower()
    args = args.strip()

    if op == "mov":
        return _encode_mov(args)
    if op == "in":
        return _encode_in(args)
    if op == "jmp":
        return _encode_jmp(args, labels)
    if op == "push":
        return _encode_push(args)

    raise ValueError(f"Unsupported instruction: {instr}")


def generate_pio_header(pio_path: Path) -> None:
    program_name = None
    instruction_lines: list[str] = []
    labels: dict[str, int] = {}
    wrap_target = None
    wrap = None

    for raw_line in pio_path.read_text(encoding="utf-8").splitlines():
        line = _sanitize_instruction(raw_line)
        if not line:
            continue

        if line.startswith(".program"):
            parts = line.split()
            if len(parts) != 2:
                raise ValueError(f"Invalid .program line in {pio_path}: {line}")
            program_name = _normalize_program_name(parts[1])
            continue

        if line == ".wrap_target":
            wrap_target = len(instruction_lines)
            continue

        if line == ".wrap":
            if len(instruction_lines) == 0:
                raise ValueError(f".wrap cannot be first directive in {pio_path}")
            wrap = len(instruction_lines) - 1
            continue

        if line.endswith(":"):
            label = line[:-1].strip().lower()
            if not label:
                raise ValueError(f"Invalid empty label in {pio_path}")
            labels[label] = len(instruction_lines)
            continue

        instruction_lines.append(line)

    if not program_name:
        raise ValueError(f"Missing .program directive in {pio_path}")
    if wrap_target is None:
        raise ValueError(f"Missing .wrap_target directive in {pio_path}")
    if wrap is None:
        raise ValueError(f"Missing .wrap directive in {pio_path}")

    encoded_lines = [_encode_instruction(instr, labels) for instr in instruction_lines]

    output = []
    output.append("#pragma once")
    output.append("")
    output.append("// AUTO-GENERATED by scripts/generate_pio_headers.py from .pio source.")
    output.append("// DO NOT EDIT THIS FILE DIRECTLY.")
    output.append("")
    output.append("#if !PICO_NO_HARDWARE")
    output.append('#include "hardware/pio.h"')
    output.append("#endif")
    output.append("")
    output.append(f"#define {program_name}_wrap_target {wrap_target}")
    output.append(f"#define {program_name}_wrap {wrap}")
    output.append("")
    output.append(f"static const uint16_t {program_name}_program_instructions[] = {{")
    for line in encoded_lines:
        output.append(f"  {line},")
    output.append("};")
    output.append("")
    output.append(f"static const struct pio_program {program_name}_program = {{")
    output.append(f"  .instructions = {program_name}_program_instructions,")
    output.append(f"  .length = {len(encoded_lines)},")
    output.append("  .origin = -1,")
    output.append("};")
    output.append("")
    output.append(f"static inline pio_sm_config {program_name}_program_get_default_config(uint offset) {{")
    output.append("  pio_sm_config c = pio_get_default_sm_config();")
    output.append(
        f"  sm_config_set_wrap(&c, offset + {program_name}_wrap_target, offset + {program_name}_wrap);"
    )
    output.append("  return c;")
    output.append("}")
    output.append("")

    pio_header_path = pio_path.with_suffix(".pio.h")
    pio_header_path.write_text("\n".join(output), encoding="utf-8")


for pio_file in PROJECT_SRC_DIR.glob("*.pio"):
    generate_pio_header(pio_file)
