#pragma once

// AUTO-GENERATED by scripts/generate_pio_headers.py from .pio source.
// DO NOT EDIT THIS FILE DIRECTLY.

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define s1s2_encoder_wrap_target 3
#define s1s2_encoder_wrap 11

static const uint16_t s1s2_encoder_program_instructions[] = {
  (uint16_t)pio_encode_mov(pio_isr, pio_null),
  (uint16_t)pio_encode_in(pio_pins, 2),
  (uint16_t)pio_encode_mov(pio_x, pio_isr),
  (uint16_t)pio_encode_mov(pio_isr, pio_null),
  (uint16_t)pio_encode_in(pio_pins, 2),
  (uint16_t)pio_encode_mov(pio_y, pio_isr),
  (uint16_t)pio_encode_jmp_x_ne_y(8),
  (uint16_t)pio_encode_jmp(3),
  (uint16_t)pio_encode_mov(pio_isr, pio_y),
  (uint16_t)pio_encode_push(false, false),
  (uint16_t)pio_encode_mov(pio_x, pio_y),
  (uint16_t)pio_encode_jmp(3),
};

static const struct pio_program s1s2_encoder_program = {
  .instructions = s1s2_encoder_program_instructions,
  .length = 12,
  .origin = -1,
};

static inline pio_sm_config s1s2_encoder_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + s1s2_encoder_wrap_target, offset + s1s2_encoder_wrap);
  return c;
}
